// Generated by build-icons.ts from svg. Do not edit it by hand:
// add or change an .svg file there, then run `bun run icons:build`.

export const ICON_VIEWBOX = '0 0 24 24'

export const icons = {
  account: '<path d="m8.973 19.3-5.436-7.309 5.406-7.104-1.044-1.431-6.093 8.01-.007 1.026 6.121 8.24z"/><path d="M10.87 1.782H8.779l7.547 10.37-7.368 10.03h2.104l7.365-10.027z"/><path d="M14.918 1.782h-2.12l7.666 10.245-7.666 10.155h2.123l7.276-9.639v-1.026z"/>',
  'arrow-left': '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.75" d="M5 12h15m-10 5.657L4.343 12 10 6.343"/>',
  'arrow-right': '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.75" d="M4 12h15m-5 5.657L19.657 12 14 6.343"/>',
  beast: '<path fill-rule="evenodd" d="m12.59 1.503-.308.009a10.95 10.95 0 0 0-4.536 1.113 11.15 11.15 0 0 0-5.679 6.476 11 11 0 0 0-.562 3.217 11 11 0 0 0 1.411 5.712 11.25 11.25 0 0 0 3.98 4.097 11.06 11.06 0 0 0 6.346 1.563 10.5 10.5 0 0 0 1.376-.166 11.1 11.1 0 0 0 6.669-4.009 11.06 11.06 0 0 0 2.395-6.163 21 21 0 0 0 0-1.491 11 11 0 0 0-1.12-4.152 11 11 0 0 0-1.692-2.505 17 17 0 0 0-.866-.866 11.1 11.1 0 0 0-3.918-2.274 11.3 11.3 0 0 0-3.148-.552 9 9 0 0 1-.348-.009m-.425 3.729a8 8 0 0 0-1.212.171 7.5 7.5 0 0 0-1.611.569l-.07.036 1.664 1.665 1.665 1.663 1.664-1.665 1.665-1.665-.072-.034a7.4 7.4 0 0 0-2.717-.731 12 12 0 0 0-.976-.009m-6.232 4.19a7.4 7.4 0 0 0-.72 2.78 7.35 7.35 0 0 0 .754 3.662l.036.07 1.665-1.664 1.662-1.663-1.665-1.665L6 9.276zm11.604 1.52-1.665 1.665 1.665 1.664 1.665 1.665.034-.072a7.4 7.4 0 0 0 .755-3.65 7.5 7.5 0 0 0-.746-2.847l-.045-.09zm-6.602 6.603-1.662 1.662.146.07a7.4 7.4 0 0 0 2.725.701c.248.015.909.008 1.142-.015a7.5 7.5 0 0 0 2.502-.687l.145-.069-1.662-1.662c-.915-.915-1.665-1.663-1.668-1.663s-.753.748-1.668 1.663" clip-rule="evenodd"/>',
  'chevron-down': '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18 9s-4.419 6-6 6-6-6-6-6"/>',
  close: '<path d="M13.46 12 19 17.54V19h-1.46L12 13.46 6.46 19H5v-1.46L10.54 12 5 6.46V5h1.46L12 10.54 17.54 5H19v1.46z"/>',
  folder: '<path d="M2.4 12.462h19.2v7.2H2.4z" opacity=".2"/><path d="M8.93 3.312a2.9 2.9 0 0 1 2.412 1.291l.813 1.22a1.1 1.1 0 0 0 .915.489h6.18a2.9 2.9 0 0 1 2.9 2.9v8.5a2.9 2.9 0 0 1-2.9 2.9H4.75a2.9 2.9 0 0 1-2.9-2.9v-11.5a2.9 2.9 0 0 1 2.9-2.9zm0 1.8H4.75a1.1 1.1 0 0 0-1.1 1.1v11.5a1.1 1.1 0 0 0 1.1 1.1h14.5a1.1 1.1 0 0 0 1.1-1.1v-8.5a1.1 1.1 0 0 0-1.1-1.1h-6.18a2.9 2.9 0 0 1-2.414-1.291L9.844 5.6a1.1 1.1 0 0 0-.916-.489z"/>',
  mechanics: '<path d="M12.006 16.805a.9.9 0 0 1 .9.9v2.039l1.178-.663a.9.9 0 0 1 1.16.241l.067.102a.9.9 0 0 1-.343 1.226l-2.03 1.14a1.91 1.91 0 0 1-1.863 0l-2.03-1.14a.9.9 0 1 1 .883-1.569l1.178.663v-2.04a.9.9 0 0 1 .778-.89zm8.25-3.953a.9.9 0 0 1 .9.9v2.306a1.9 1.9 0 0 1-.968 1.656l-2.17 1.22a.9.9 0 1 1-.882-1.568l1.303-.733-1.73-1a.9.9 0 0 1-.383-1.119l.054-.11a.9.9 0 0 1 1.23-.33l1.748 1.01v-1.332a.9.9 0 0 1 .778-.892l.122-.008zm-16.5 0a.9.9 0 0 1 .9.9v1.332l1.748-1.01a.9.9 0 0 1 1.162.228l.068.102a.9.9 0 0 1-.33 1.23l-1.731 1 1.304.732a.9.9 0 0 1 .396 1.115l-.053.11a.9.9 0 0 1-1.225.344l-2.17-1.22a1.9 1.9 0 0 1-.968-1.657v-2.306a.9.9 0 0 1 .9-.9zm13.036-7.439a.9.9 0 0 1 1.225-.343l2.17 1.22a1.9 1.9 0 0 1 .968 1.656v2.306a.9.9 0 1 1-1.8 0V8.918l-1.708.988a.9.9 0 0 1-1.161-.228l-.069-.102a.9.9 0 0 1 .33-1.23l1.691-.977-1.303-.732a.9.9 0 0 1-.396-1.115zM5.994 5.07a.9.9 0 1 1 .882 1.568l-1.304.732 1.69.977a.9.9 0 0 1 .383 1.12l-.054.11a.9.9 0 0 1-1.23.33L4.656 8.92v1.332a.9.9 0 0 1-.778.891l-.122.009a.9.9 0 0 1-.9-.9V7.946c0-.686.37-1.32.968-1.656zm5.08-2.857a1.91 1.91 0 0 1 1.863 0l2.03 1.141a.9.9 0 0 1-.883 1.568l-1.178-.663v1.993a.9.9 0 0 1-.778.892l-.122.008a.9.9 0 0 1-.9-.9V4.259l-1.178.663a.9.9 0 0 1-1.16-.24l-.067-.103a.9.9 0 0 1 .343-1.225z"/>',
  menu: '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 6h10M4 12h16M7 12h13M7 18h10"/>',
  'new-folder': '<path d="M5.244 13.356a.9.9 0 0 1 .9.9v2.1h2.1a.9.9 0 0 1 .892.778l.008.122a.9.9 0 0 1-.9.9h-2.1v2.1a.9.9 0 0 1-.778.892l-.122.008a.9.9 0 0 1-.9-.9v-2.1h-2.1a.9.9 0 0 1-.892-.778l-.008-.122a.9.9 0 0 1 .9-.9h2.1v-2.1a.9.9 0 0 1 .778-.892zm4.18-10.5a2.9 2.9 0 0 1 2.413 1.291l.812 1.22a1.1 1.1 0 0 0 .916.489h6.18a2.9 2.9 0 0 1 2.9 2.9v8.5a2.9 2.9 0 0 1-2.9 2.9h-8.501a.9.9 0 1 1 0-1.8h8.5a1.1 1.1 0 0 0 1.1-1.1v-8.5a1.1 1.1 0 0 0-1.1-1.1h-6.18a2.9 2.9 0 0 1-2.414-1.291l-.812-1.22a1.1 1.1 0 0 0-.916-.489H5.244a1.1 1.1 0 0 0-1.1 1.1v5.5a.9.9 0 0 1-1.8 0v-5.5a2.9 2.9 0 0 1 2.9-2.9z"/>',
  're-up.ph': '<path d="M12 18h6v-5.812c0-.157-.034-.189-.187-.188H12zm6 0v4.81c0 .657.533 1.19 1.19 1.19H24v-4.81A1.19 1.19 0 0 0 22.81 18z"/><path d="M24 10.81V1.19A1.19 1.19 0 0 0 22.81 0H1.19A1.19 1.19 0 0 0 0 1.19v21.62C0 23.467.533 24 1.19 24h9.62A1.19 1.19 0 0 0 12 22.81V18H6V6h12v6h4.81A1.19 1.19 0 0 0 24 10.81"/>',
  search: '<path fill-rule="evenodd" d="M2.25 9.75a7.5 7.5 0 1 1 15 0 7.5 7.5 0 0 1-15 0M9.75 0a9.75 9.75 0 1 0 6.06 17.4l5.145 5.145.795.795 1.59-1.59-.795-.795L17.4 15.81A9.75 9.75 0 0 0 9.75 0" clip-rule="evenodd" shape-rendering="geometricprecision"/>',
  sidebar: '<path fill-rule="evenodd" d="M6.416 3A4.416 4.416 0 0 0 2 7.416v8.833a4.415 4.415 0 0 0 4.416 4.417h11.168A4.415 4.415 0 0 0 22 16.248V7.416A4.416 4.416 0 0 0 17.584 3zm5.228 1.767a2 2 0 0 0-2 2v10.132a2 2 0 0 0 2 2h5.94a2.65 2.65 0 0 0 2.65-2.65V7.416a2.65 2.65 0 0 0-2.65-2.65z" clip-rule="evenodd"/>',
  'spinner-ring': '<path fill="currentColor" d="M12,1A11,11,0,1,0,23,12,11,11,0,0,0,12,1Zm0,19a8,8,0,1,1,8-8A8,8,0,0,1,12,20Z" opacity=".25"/><path fill="currentColor" d="M10.14,1.16a11,11,0,0,0-9,8.92A1.59,1.59,0,0,0,2.46,12,1.52,1.52,0,0,0,4.11,10.7a8,8,0,0,1,6.66-6.61A1.42,1.42,0,0,0,12,2.69h0A1.57,1.57,0,0,0,10.14,1.16Z"><animateTransform attributeName="transform" dur="0.75s" repeatCount="indefinite" type="rotate" values="0 12 12;360 12 12"/></path>',
  switch: '<path fill-rule="evenodd" d="M9 5.25h6a6.75 6.75 0 1 1 0 13.5H9a6.75 6.75 0 1 1 0-13.5M0 12a9 9 0 0 1 9-9h6a9 9 0 0 1 0 18H9a9 9 0 0 1-9-9m15 4.5a4.5 4.5 0 1 0 0-9 4.5 4.5 0 0 0 0 9" clip-rule="evenodd" shape-rendering="geometricprecision"/>',
  theme: '<g fill="none"><path fill="currentColor" d="M2.75 12A9.25 9.25 0 0 0 12 21.25V2.75A9.25 9.25 0 0 0 2.75 12"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M12 21.25a9.25 9.25 0 0 0 0-18.5m0 18.5a9.25 9.25 0 0 1 0-18.5m0 18.5V2.75"/></g>',
  timeline: '<path d="M15.565 9.472a.9.9 0 0 1 1.61 0l1.365 2.73 2.732 1.366a.9.9 0 0 1 .117 1.541l-.117.07-2.732 1.367-1.364 2.73a.9.9 0 0 1-1.541.117l-.07-.116-1.367-2.733-2.73-1.365a.9.9 0 0 1-.117-1.541l.116-.07 2.73-1.365zM6.62 16.724a.9.9 0 1 1 0 1.8h-3.5a.9.9 0 1 1 0-1.8zm9.75-4.838-.694 1.39a.9.9 0 0 1-.402.403l-1.39.695 1.39.694a.9.9 0 0 1 .344.303l.059.1.693 1.389.696-1.388a.9.9 0 0 1 .303-.345l.1-.059 1.39-.694-1.39-.695a.9.9 0 0 1-.344-.303l-.059-.1zm-7.75-1.412a.9.9 0 1 1 0 1.8h-5.5a.9.9 0 1 1 0-1.8zm11-6.25a.9.9 0 0 1 0 1.8H3.12a.9.9 0 0 1 0-1.8z"/>',
}

export type IconName = keyof typeof icons

/** Scope SVG definitions and their references to one framework useId() value. */
export function iconMarkup(name: IconName, instanceId: string): string {
  const body = icons[name]
  const ids = new Map([...body.matchAll(/\sid="([^"]+)"/g)].map(([, id]) => [id, `icon-${Array.from(instanceId, c => c.codePointAt(0)!.toString(16)).join('-')}-${id}`]))
  if (!ids.size) return body
  const scoped = (id: string) => ids.get(id) ?? id
  let markup = body.replace(/ (id|href|xlink:href|aria-labelledby|aria-describedby|begin|end)="([^"]*)"/g, (attribute, key: string, value: string) => {
    if (key === 'id') return ` id="${scoped(value)}"`
    if (key === 'href' || key === 'xlink:href') return ` ${key}="${value.startsWith('#') ? '#' + scoped(value.slice(1)) : value}"`
    if (key.startsWith('aria-')) return ` ${key}="${value.split(/\s+/).map(scoped).join(' ')}"`
    return ` ${key}="${value.split(';').map(part => {
      const leading = part.match(/^\s*/)?.[0] ?? ''
      const timing = part.trimStart()
      // Longest first: IDs may contain dots, as may animation event names.
      const id = [...ids.keys()].sort((a, b) => b.length - a.length).find(id => timing.startsWith(id + '.'))
      return id ? leading + scoped(id) + timing.slice(id.length) : part
    }).join(';')}"`
  })
  markup = markup.replace(/url\(\s*(['"]?)#([^\s)'"]+)\1\s*\)/g, (_, quote: string, id: string) => `url(${quote}#${scoped(id)}${quote})`)
  // SVGO prefixes stylesheet selectors at build time; scope them at render time too.
  return markup.replace(/<style([^>]*)>([\s\S]*?)<\/style>/g, (_, attributes: string, css: string) =>
    `<style${attributes}>${css.replace(/#((?:\\.|[a-zA-Z0-9_-])+)/g, (match, selector: string) => {
      const id = selector.replace(/\\(.)/g, '$1')
      return ids.has(id) ? '#' + scoped(id).replace(/\./g, '\\.') : match
    })}</style>`)
}
