import Home from './Home.btsx'
import Converters from './Converters.btsx'
import ImageConverter from './ImageConverter.btsx'
import Icons from './Icons.btsx'
import IconSet from './IconSet.btsx'
import IconFavorites from './IconFavorites.btsx'
import IconDetail from './IconDetail.btsx'
import Gym from './Gym.btsx'
import EffectJs from './EffectJs.btsx'
export { Home, Converters, ImageConverter, Icons, IconSet, IconFavorites, IconDetail, Gym, EffectJs }
